name: Run NPM Audit

on:
  push:
    branches: [ "develop" ]

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cv-app-front
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v3
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
          working_directory: ./cv-app-front
