name: Frontend CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  angular:
    name: Angular Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cv-app-front
    strategy:
      matrix:
        node-version: [ '21.x' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: cv-app-front/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
      - name: Build application
        run: npm run build